version: '3'

services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: "0.0.1-SNAPSHOT"
    ports:
      - "80:8080"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      MYSQL_HOST: "mysql:3306"
      MYSQL_DATABASE: "anymind_pos"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: "root"


  mysql:
    image: 'mysql:8'
    volumes:
      - data_mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: 'anymind_pos'

volumes:
  data_mysql: { }
